language: r
sudo: required
dist: xenial
r:
  - release
  - devel
  - oldrel
addons:
  apt:
    packages:
     - libgdal-dev
     - libproj-dev 
     - libgeos-dev
     - libudunits2-dev 
warnings_are_errors: true
r_packages:
  - SpatialPosition
  - knitr
  - rmarkdown
  - testthat
  - covr
  - rgdal
after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'